Repository croct-tech/schemas, pull requests merged in 2025-04, with the labels that each got.

#7 Fix schema
  .github/workflows/deploy-schemas.yaml
  README.md
  packages/json-schemas/schemas/project.json
Labels: bug

#8 Fix schema IDs and add project schema to readme
  .github/workflows/deploy-schemas.yaml
  README.md
Labels: bug

#10 Fix version path
  .github/workflows/deploy-schemas.yaml
Labels: maintenance

#12 Add description to options
  packages/json-schemas/schemas/template/template.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/template-invalid-properties.json
  packages/json-schemas/test/schemas/fixtures/template/valid/template-complete.json
Labels: bug

#13 Add the new overwrite option
  packages/json-schemas/schemas/template/action/download.json
  packages/json-schemas/test/schemas/fixtures/template/valid/action/download-complete.json
Labels: feature

#14 Update template schema
  packages/json-schemas/schemas/template/template.json
Labels: maintenance

#16 Fix dynamic value pattern
  packages/json-schemas/scripts/template-schema-transformer.ts
  packages/json-schemas/test/scripts/fixtures/template-transformer/additional-properties-false.json
  packages/json-schemas/test/scripts/template-schema-transformer.test.ts
Labels: bug

#15 Add missing required option
  packages/json-schemas/schemas/template/template.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/template-invalid-properties.json
  packages/json-schemas/test/schemas/fixtures/template/valid/template-complete.json
Labels: bug

#17 Update project paths
  packages/json-schemas/schemas/project.json
  packages/json-schemas/test/schemas/fixtures/project/invalid/project-empty.json
  packages/json-schemas/test/schemas/fixtures/project/valid/project-complete.json
  packages/json-schemas/test/schemas/fixtures/project/valid/project-minimum.json
Labels: maintenance

#18 Add the new mapping option
  packages/json-schemas/schemas/template/action/download.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/download-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/valid/action/download-complete.json
Labels: feature

#19 Fix create resource schema
  packages/json-schemas/schemas/template/action/create-resource.json
Labels: bug

#22 Add schema for template metadata
  .github/workflows/deploy-schemas.yaml
  packages/json-schemas/schemas/template/catalog-metadata.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/catalog-metadata-empty.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/catalog-metadata-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/valid/catalog-metadata-complete.json
Labels: feature

#21 Correct type for experiment variant allocation field
  packages/json-schemas/schemas/template/action/create-resource.json
  packages/json-schemas/test/schemas/fixtures/template/valid/action/create-resource-complete.json
Labels: bug

#23 Rename template catalog metadata
  .github/workflows/deploy-schemas.yaml
  README.md
  packages/json-schemas/schemas/template/template-catalog-metadata.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/catalog-metadata-empty.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/catalog-metadata-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/valid/catalog-metadata-complete.json
Labels: maintenance

#24 Remove $schema from actions
  .github/workflows/deploy-schemas.yaml
Labels: bug

#27 Remove nested schema props
  .github/workflows/deploy-schemas.yaml
  packages/json-schemas/bin/clean-nested-schema-props.ts
  packages/json-schemas/scripts/nested-schema-prop-cleaner.ts
  packages/json-schemas/test/scripts/nested-schema-prop-cleaner.test.ts
Labels: bug

#26 Fix try schema
  packages/json-schemas/schemas/template/action/try.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/repeat-empty-action-list.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/repeat-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/run-empty-action-list.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/run-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/test-empty-action-list.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/test-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/try-else-help.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/try-empty-lists.json
Labels: bug

#28 Fix schema props
  packages/json-schemas/schemas/content-schema.json
  packages/json-schemas/schemas/content.json
  packages/json-schemas/schemas/template/action.json
  packages/json-schemas/schemas/template/catalog-template.json
Labels: bug

#29 Fix template ID patterns
  packages/json-schemas/schemas/template/catalog-template-metadata.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/catalog-template-extra-property.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/catalog-template-metadata-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/valid/catalog-template-complete.json
  packages/json-schemas/test/schemas/fixtures/template/valid/catalog-template-metadata-complete.json
Labels: bug

#30 Refactor catalog template
  .github/workflows/deploy-schemas.yaml
  packages/json-schemas/bin/merge-schemas.ts
  packages/json-schemas/package-lock.json
  packages/json-schemas/package.json
  packages/json-schemas/schemas/template/catalog-template-metadata.json
  packages/json-schemas/schemas/template/catalog-template.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/catalog-template-empty-metadata.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/catalog-template-extra-property.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/catalog-template-metadata-empty.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/catalog-template-metadata-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/valid/catalog-template-metadata-complete.json
Labels: bug

#31 Fix dependencies
  packages/json-schemas/package-lock.json
  packages/json-schemas/package.json
Labels: bug

#32 Fix build
  .github/workflows/deploy-schemas.yaml
Labels: bug

#33 Change documentation metadata to be a URL
  packages/json-schemas/schemas/template/catalog-template.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/catalog-template-empty-metadata.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/catalog-template-extra-property.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/catalog-template-metadata-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/valid/catalog-template-complete.json
Labels: maintenance

#35 Remove minimum number of items
  packages/json-schemas/schemas/template/action/create-resource.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/create-resource-empty-lists.json
Labels: bug

#36 Fix create-resource validation
  packages/json-schemas/schemas/template/action/create-resource.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/create-resource-empty-lists.json
Labels: bug
