Repository croct-tech/schemas, pull requests merged in 2025-05, with the labels that each got.

#38 Update schemas
  packages/json-schemas/schemas/template/action/execute-package.json
  packages/json-schemas/schemas/template/action/start-server.json
  packages/json-schemas/schemas/template/action/stop-server.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/start-server-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/stop-server-empty.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/stop-server-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/valid/action/execute-package-boolean-interactions.json
  packages/json-schemas/test/schemas/fixtures/template/valid/action/start-server-complete.json
  packages/json-schemas/test/schemas/fixtures/template/valid/action/stop-server-complete.json
  packages/json-schemas/test/schemas/fixtures/template/valid/template-complete.json
Labels: maintenance

#39 Add template schema for content and content schema
  .github/workflows/deploy-schemas.yaml
  README.md
  packages/json-schemas/bin/generate-content-definition-schema.ts
  packages/json-schemas/bin/generate-content-schema.ts
  packages/json-schemas/bin/process-template-schema.ts
  packages/json-schemas/bin/transform-dynamic-schema.ts
  packages/json-schemas/scripts/dynamic-schema-transformer.ts
  packages/json-schemas/test/scripts/dynamic-schema-transformer.test.ts
  packages/json-schemas/test/scripts/fixtures/template-transformer/root-actions-property.json
  packages/json-schemas/test/scripts/fixtures/template-transformer/root-properties.json
  packages/json-schemas/tsconfig.json
Labels: feature

#40 Template installationUrl
  packages/json-schemas/schemas/template/catalog-template.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/catalog-template-empty-metadata.json
Labels: enhancement

#42 Remove extra unevaluated properties
  packages/json-schemas/schemas/content-schema.json
  packages/json-schemas/schemas/content.json
Labels: bug

#43 Rename author to ecosystem
  packages/json-schemas/schemas/template/catalog-template.json
  packages/json-schemas/test/schemas/fixtures/event/valid/payload/post-viewed-complete.json
  packages/json-schemas/test/schemas/fixtures/event/valid/payload/post-viewed-minimal.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/catalog-template-empty-metadata.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/catalog-template-extra-property.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/catalog-template-metadata-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/valid/catalog-template-complete.json
  packages/json-schemas/test/schemas/fixtures/template/valid/template-complete.json
Labels: maintenance

#44 Update schemas with the latest changes
  packages/json-schemas/schemas/template/action.json
  packages/json-schemas/schemas/template/action/create-directory.json
  packages/json-schemas/schemas/template/action/install.json
  packages/json-schemas/schemas/template/action/integrate-croct.json
  packages/json-schemas/schemas/template/action/locate-path.json
  packages/json-schemas/schemas/template/action/move-path.json
  packages/json-schemas/schemas/template/action/read-file.json
  packages/json-schemas/schemas/template/action/write-file.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/create-directory-empty.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/create-directory-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/install-empty.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/install-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/integrate-croct-empty.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/integrate-croct-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/locate-path-empty-matcher-list.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/locate-path-empty.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/locate-path-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/move-path-empty.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/move-path-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/read-file-empty.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/read-file-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/write-file-empty.json
  packages/json-schemas/test/schemas/fixtures/template/invalid/action/write-file-invalid-property-values.json
  packages/json-schemas/test/schemas/fixtures/template/valid/action/create-directory-complete.json
  packages/json-schemas/test/schemas/fixtures/template/valid/action/install-complete.json
  packages/json-schemas/test/schemas/fixtures/template/valid/action/integrate-croct-complete.json
  packages/json-schemas/test/schemas/fixtures/template/valid/action/locate-path-complete.json
  packages/json-schemas/test/schemas/fixtures/template/valid/action/locate-path-minimum.json
  packages/json-schemas/test/schemas/fixtures/template/valid/action/move-path-complete.json
  packages/json-schemas/test/schemas/fixtures/template/valid/action/move-path-minimum.json
  packages/json-schemas/test/schemas/fixtures/template/valid/action/read-file-complete.json
  packages/json-schemas/test/schemas/fixtures/template/valid/action/read-file-minimum.json
  packages/json-schemas/test/schemas/fixtures/template/valid/action/write-file-complete.json
  packages/json-schemas/test/schemas/fixtures/template/valid/action/write-file-empty-content.json
  packages/json-schemas/test/schemas/fixtures/template/valid/action/write-file-minimum.json
  packages/json-schemas/test/schemas/fixtures/template/valid/template-complete.json
Labels: maintenance
